---
- name: Generate Configuration Report
  hosts: web_servers
  gather_facts: yes

  tasks:
    - name: Create destination directory if not exists
      ansible.builtin.file:
        path: "/etc/collect/report"
        state: directory

    - name: Gather system information
      ansible.builtin.setup:
        filter: ansible_facts

    - name: Include facts about network interfaces
      ansible.builtin.setup:
        filter: network

    - name: Gather IP address (fallback to 'N/A' if 'ansible_default_ipv4' not available)
      set_fact:
        ip_address: "{{ query('first', ansible_facts['ansible_default_ipv4']['address']) | default('N/A') }}"
      ignore_errors: true

    - name: Gather memory information
      ansible.builtin.debug:
        var: ansible_facts['ansible_memory_mb']

    - name: Gather disk information
      ansible.builtin.debug:
        var: ansible_facts['ansible_mounts']

    - name: Gather firewall configuration
      ansible.builtin.shell:
        cmd: iptables -L
      register: firewall_output

    - name: Get crontab entries for all users
      ansible.builtin.shell:
        cmd: "for user in $(getent passwd | cut -d: -f1); do crontab -l -u $user || true; done"
      register: crontab_result

    - name: Save crontab entries to a fact variable
      ansible.builtin.set_fact:
        crontab_config: "{{ crontab_result.stdout_lines | default([]) | join('\n') }}"

    - name: Get sudo rules for all users
      ansible.builtin.shell:
        cmd: "for user in $(getent passwd | cut -d: -f1); do sudo -U $user -l || true; done"
      register: sudo_rules_result

    - name: Save sudo rules to a fact variable
      ansible.builtin.set_fact:
        sudo_rules: "{{ sudo_rules_result.stdout_lines | join('\n') }}"

    - name: Generate CSV report
      ansible.builtin.template:
        src: report.j2
        dest: "/etc/collect/report/server_report.csv"
      ignore_errors: true
      vars:
        ip_address: "{{ ansible_facts['ansible_default_ipv4']['address'] | default('N/A', true) }}"
        firewall_config: "{{ firewall_output.stdout_lines | join('\n') | default('N/A', true) }}"
        crontab_entries: "{{ crontab_config | default('N/A', true) }}"
        sudo_rules: "{{ sudo_rules | default('N/A', true) }}"
